name: readme-scribe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'
  push:
    branches:
      - 'master'

jobs:
  readme-scribe:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission for stefanzweifel/git-auto-commit-action 
      # to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Required permissions:
      # - read:user, repo:status, public_repo, read:org
      - uses: muesli/readme-scribe@5a187a2a36ef894335f17a7d01c32b0e28c6d948
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.README_SCRIBE_GH_PAT }}

      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
        with:
          commit_message: 'Update generated README'
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
